services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://cyberuser:cyberpass@db:5432/cyberverse?schema=public
      - JWT_SECRET=your_secret_key
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=cyberuser
      - POSTGRES_PASSWORD=cyberpass
      - POSTGRES_DB=cyberverse
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cyberuser -d cyberverse"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'

volumes:
  postgres_data:
  redis_data:
